name: liquid_expense_manager
description: Elite Liquid Glass Expense Manager.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.0
  pdf: ^3.10.8
  printing: ^5.11.1
  liquid_glass_widgets: ^0.9.6
  intl: ^0.19.0
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true
